services:
  service:
    build: .
    ports:
      - "9055:9055"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BRAINBOOST_COCKROACH_DB=${BRAINBOOST_COCKROACH_DB}
      - PINECONE_KEY=${PINECONE_KEY}
      - PINECONE_URL=${PINECONE_URL}
  gateway:
    build:
      context: ./envoy
    ports:
      - "8080:8080"
