version: "3.8"

services:
  # Qdrant is a vector search engine
  vectordb:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"

  # Create a MongoDB instance
  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"

  # Backend is the service that handles requests from the frontend
  backend:
    build: .
    ports:
      - "9055:9055"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHATBOT_DB=postgresql://root@database:26257/defaultdb?sslmode=disable
      - CHATBOT_MONGODB_URI=mongodb://mongodb:27017
      - CHATBOT_QDRANT_URL=vectordb:6334
      - CHATBOT_QDRANT_INSECURE=true
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./service_account.json:/service_account.json
    depends_on:
      mongo:
        condition: service_started
      vectordb:
        condition: service_started

  # Envoy is a proxy that translates gRPC-web requests to gRPC
  gateway:
    build:
      context: ./envoy
    ports:
      - "8080:8080"
    depends_on:
      - backend