services:
  service:
    build: .
    ports:
      - "9055:9055"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_DB=${SUPABASE_DB}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_STORAGE_TOKEN=${SUPABASE_STORAGE_TOKEN}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
  gateway:
    build:
      context: ./envoy
    ports:
      - "8080:8080"
